name: Release Xodex

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      # Publish on any tag starting with a `v`, e.g., v1.0.0
      - "v*" # Push events to matching v*, i.e. v1.0.0

    # branches: "release/**"

jobs:
  release-build:
    name: Build Xodex Distributions.

    strategy:
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Set Uv & Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install Package dependencies
        run: |
          uv sync --frozen

      - name: Build distributions
        run: |
          uv build
          uv run twine check dist/*

  release:
    name: Create Xodex Release.

    needs:
      - release-build

    permissions:
      id-token: write
      contents: write
      attestations: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download all artifacts
        uses: actions/download-artifact@v6
        with:
          path: dist/
          merge-multiple: true

      - name: Get Release Version
        id: version
        run: echo "VER=${GITHUB_REF_NAME#'refs/tags/'}" >> $GITHUB_OUTPUT

      - name: Generate Release Attestation
        uses: actions/attest-build-provenance@v3.0.0
        with:
          subject-path: "dist/*"

      - name: Create Tag Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          # draft: true
          name: Xodex ${{ steps.version.outputs.VER }} release
          tag_name: ${{ contains(steps.version.outputs.VER, 'dev') }}
          prerelease: ${{ contains(steps.version.outputs.VER, 'dev') }}
          # target_commitish: ${{ github.ref_name }}
          generate_release_notes: true
          files: dist/*
